### ISSUE TITLE
Default language URL

### ISSUE THREAD

**Issue by vlaxis** [angeloocana/gatsby-starter-default-i18n#1]
Hello! I've changed the default language from 'en' to 'pt' but on page refresh, the URL is auto-switched to '/en'. Any fixes for this?

**Comment by angeloocana** [comment]
Hello @vlaxis !

What is your browser language?

**Comment by vlaxis** [comment]
Hi @angeloocana, it was english. Changed the browser language and everything works as expected, thanks for the quick response! :D

**Comment by angeloocana** [comment]
You are welcome @vlaxis =D

I'm happy that it is not a bug =D uhuhuhuh
