### ISSUE TITLE
Production build absolute path error

### ISSUE THREAD

**Issue by vlaxis** [angeloocana/gatsby-starter-default-i18n#2]
Hello! I've tried to build and run the gatsby project with ```gatsby build``` and ```gatsby serve``` and deploy to Surge, but I get the following error. I can't find any answers related to this issue. Do you know what's going on? Everything works ok when I'm developing. By the way, great work!

<img width="1440" alt="screen shot 2017-10-19 at 21 10 19" src="https://user-images.githubusercontent.com/12220618/31786767-3d437842-b512-11e7-9493-59360eaafdf6.png">

**Comment by angeloocana** [comment]
Hello @vlaxis !
I could not reproduce the error. =/

Is your project on github? I can try using it.

Are you using **yarn** or **npm**?

You said that the error happens when you deploy to surge,
but the print is from localhost:9000. Is it right?

**Comment by vlaxis** [comment]
Hello again @angeloocana.
So the problem should be at **npm** itself. Now it works as expected by following these steps:

```rm -rf node_modules```
```rm -rf .cache```
```rm -rf public```
```yarn```
```gatsby build```
```gatsby serve```

So the error occured at the moment I wrote ```npm install``` with **node v8.7.0** and **npm 5.4.2**.

Thanks and have a great day!

**Comment by angeloocana** [comment]
=D Great! I had problems with npm too.

All the best!
