### ISSUE TITLE
History is messed up by automatic language detection

### ISSUE THREAD

**Issue by zcserei** [angeloocana/gatsby-starter-default-i18n#4]
The problem is visible in the demo: you cannot go back to the previous page in history since you are automatically redirected to one of the language versions, in my case, to /en.

I tried in Chrome and Firefox.

**Comment by zcserei** [comment]
The same problem is apparent in the case of your personal website as well, @angeloocana.

**Comment by angeloocana** [comment]
Thank you @zcserei for finding and reporting the bug!

It`s fixed!

I don`t think this is the best solution,
I would like to use Gatsby Redirects like: 
https://github.com/gatsbyjs/gatsby/tree/master/examples/using-redirects
But Gatsby Redirects are static, they need to be specified at build time,
This redirect is dynamic, It needs to know the user browser language.

Any suggestions?

I'll be closing this issue, but feel free to reopen it.

**Comment by cbix** [comment]
> Any suggestions?

Server side detection and redirects. But you'll need sufficient control over the webserver configuration.

For static sites hosted on Netlify, I found this method: https://docs.netlify.com/routing/redirects/redirect-options/#redirect-by-country-or-language
Which can also be configured using a toml configuration file: https://docs.netlify.com/routing/redirects/#syntax-for-the-netlify-configuration-file
